version: '3'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=${PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
  web:
    image:  softerrific/opt_out_api:0.1.0
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db